@startuml
actor "고객" as Customer

rectangle "상품 검색 실패" {
  usecase "<UC1_1_failure> 태그 선택 실패" as UC1_1_failure
  note right
  태그 선택 실패:
  - 태그 입력 값 누락
  - 유효하지 않은 태그 입력
  end note

  usecase "<UC1_2_failure> 카테고리별 필터 적용 실패" as UC1_2_failure
  note right
  카테고리별 필터 적용 실패:
  - 필터 조건 미적용
  - 잘못된 필터 조건 입력
  end note
}

Customer --> UC1_1_failure
Customer --> UC1_2_failure
@enduml
